from tests.unit.domain.constants.common import (
    CHANNEL_ACTIVE_THRESHOLD,
    CHANNEL_MIN_ID_DIFF,
    DEFAULT_COUNT,
    DEFAULT_CURRENT_ID,
    DEFAULT_LAST_ID,
    LAST_POST_ID,
    MESSAGE_OFFSET,
    NUM1,
    NUM2,
    NUM3,
)
from tests.unit.domain.constants.fixtures.channel import (
    CHANNEL_AVAILABLE,
    CHANNEL_BASE,
    CHANNEL_BASE_SAMPLE,
    CHANNEL_BASE_SAMPLE_CURRENT_EQUAL_LAST,
    CHANNEL_BASE_SAMPLE_CURRENT_GT_LAST,
    CHANNEL_CURRENT_ID_BY_NAME,
    CHANNEL_CURRENT_ID_BY_NAMES,
    CHANNEL_DEFAULT_LAST_ID,
    CHANNEL_INFO_BY_NAME,
    CHANNEL_INFO_BY_NAMES,
    CHANNEL_MISSING_COUNT,
    CHANNEL_MISSING_LAST_ID,
    CHANNEL_NAMES_SAMPLE,
    CHANNEL_NEGATIVE_CURRENT_ID,
    CHANNEL_NEW,
    CHANNEL_SCANNED_NO_FOUND_CONFIGS,
    CHANNEL_ZERO_CURRENT_ID,
    CHANNELS_FROM_NAMES_SAMPLE,
    CHANNELS_SAMPLE,
)

__all__ = [
    "ASSIGN_CURRENT_ID_TO_CHANNELS_INVALID_OFFSET_EXAMPLES",
    "ASSIGN_CURRENT_ID_TO_CHANNELS_VARIOUS_EXAMPLES",
    "DELETE_CHANNELS_EXAMPLES",
    "DIFF_CHANNEL_ID_EXAMPLES",
    "FORMAT_CHANNEL_STATUS_EXAMPLES",
    "GET_FILTERED_KEYS_EXAMPLES",
    "GET_NORMALIZED_CURRENT_ID_EXAMPLES",
    "GET_SORTED_KEYS_EXAMPLES",
    "NORMALIZE_CHANNEL_NAMES_EXAMPLES",
    "PRINT_CHANNEL_INFO_VARIOUS_EXAMPLES",
    "PROCESS_CHANNELS_CALLS_EXAMPLES",
    "SORT_CHANNEL_NAMES_EXAMPLES",
    "UPDATE_COUNT_AND_LAST_ID_EXAMPLES",
    "UPDATE_WITH_NEW_CHANNELS_EXAMPLES",
]

ASSIGN_CURRENT_ID_TO_CHANNELS_INVALID_OFFSET_EXAMPLES: tuple[
    tuple[
        int | str,
        str,
    ],
    ...,
] = (
    (
        -10,
        "negative_offset",
    ),
    (
        "abc",
        "non_int_offset",
    ),
    (
        0,
        "zero_offset",
    ),
)

ASSIGN_CURRENT_ID_TO_CHANNELS_VARIOUS_EXAMPLES: tuple[
    tuple[
        dict[str, dict[str, int]],
        int,
        bool,
        dict[str, int | None],
        str,
    ],
    ...,
] = (
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_available",
            "channel_new",
            "channel_unavailable",
        ]),
        MESSAGE_OFFSET,
        True,
        CHANNEL_CURRENT_ID_BY_NAMES([
            "channel_available",
            "channel_new",
            "channel_unavailable",
        ]),
        "mixed_check_only",
    ),
    (
        CHANNEL_INFO_BY_NAME(
            "channel_new",
        ),
        MESSAGE_OFFSET,
        False,
        CHANNEL_CURRENT_ID_BY_NAME(
            "channel_new",
        ),
        "new_channel",
    ),
    (
        CHANNEL_INFO_BY_NAME(
            "channel_available",
        ),
        MESSAGE_OFFSET,
        False,
        {
            "channel_available": NUM3 - MESSAGE_OFFSET,
        },
        "normal_channel",
    ),
    (
        CHANNEL_INFO_BY_NAME(
            "channel_unavailable",
        ),
        MESSAGE_OFFSET,
        False,
        CHANNEL_CURRENT_ID_BY_NAME(
            "channel_unavailable",
        ),
        "unavailable_channel",
    ),
)

DELETE_CHANNELS_EXAMPLES: tuple[
    tuple[
        object,
        list[str],
        list[str],
        str,
    ],
    ...,
] = (
    (
        {
            channel_name: {
                **CHANNEL_AVAILABLE,
            }
            for channel_name in CHANNEL_NAMES_SAMPLE
        },
        CHANNEL_NAMES_SAMPLE,
        [],
        "all_channels_available",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_scanned_no_found_configs",
            "channel_scanned_below_remove_threshold",
            "channel_scanned_remove_threshold",
        ]),
        [],
        [
            "channel_scanned_no_found_configs",
            "channel_scanned_below_remove_threshold",
            "channel_scanned_remove_threshold",
        ],
        "all_channels_delete",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_available",
            "channel_default_count_and_current_gt_last",
            "channel_new",
        ]),
        [
            "channel_available",
            "channel_new",
        ],
        [
            "channel_default_count_and_current_gt_last",
        ],
        "boundary_values",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_base_current_gt_last",
            "channel_default_count_and_current_gt_last",
            "channel_scanned_found_configs",
        ]),
        [
            "channel_base_current_gt_last",
            "channel_scanned_found_configs",
        ],
        [
            "channel_default_count_and_current_gt_last",
        ],
        "current_gt_last",
    ),
    (
        {},
        [],
        [],
        "empty",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_removed",
            "channel_removed_below_threshold",
            "channel_scanned_found_configs",
        ]),
        [
            "channel_scanned_found_configs",
        ],
        [
            "channel_removed",
            "channel_removed_below_threshold",
        ],
        "failed_threshold",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_scanned_found_configs",
            "channel_scanned_no_found_configs",
        ]),
        [
            "channel_scanned_found_configs",
        ],
        [
            "channel_scanned_no_found_configs",
        ],
        "one_delete",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_base_current_lt_last",
            "channel_default_count_and_current_gt_last",
            "channel_scanned_below_remove_threshold",
        ]),
        [
            "channel_base_current_lt_last",
        ],
        [
            "channel_default_count_and_current_gt_last",
            "channel_scanned_below_remove_threshold",
        ],
        "partial_delete",
    ),
)

DIFF_CHANNEL_ID_EXAMPLES: tuple[
    tuple[
        dict[str, object],
        int,
        str,
    ],
    ...,
] = (
    (
        CHANNEL_BASE_SAMPLE_CURRENT_GT_LAST,
        max(
            CHANNEL_MIN_ID_DIFF,
            NUM2 - min(NUM3, NUM2),
        ),
        "current_greater_than_last",
    ),
    (
        {},
        max(
            CHANNEL_MIN_ID_DIFF,
            DEFAULT_LAST_ID - DEFAULT_CURRENT_ID,
        ),
        "empty_channel",
    ),
    (
        CHANNEL_DEFAULT_LAST_ID,
        max(
            CHANNEL_MIN_ID_DIFF,
            DEFAULT_LAST_ID - DEFAULT_CURRENT_ID,
        ),
        "last_id_default",
    ),
    (
        {
            **CHANNEL_BASE_SAMPLE,
            "current_id": -MESSAGE_OFFSET,
        },
        max(
            CHANNEL_MIN_ID_DIFF,
            NUM3 - (NUM3 + -MESSAGE_OFFSET),
        ),
        "negative_current",
    ),
    (
        CHANNEL_NEW,
        max(
            CHANNEL_MIN_ID_DIFF,
            DEFAULT_LAST_ID - DEFAULT_CURRENT_ID,
        ),
        "new_channel",
    ),
    (
        CHANNEL_BASE_SAMPLE,
        max(
            CHANNEL_MIN_ID_DIFF,
            NUM3 - NUM2,
        ),
        "normal_difference",
    ),
)

FORMAT_CHANNEL_STATUS_EXAMPLES: tuple[
    tuple[
        str,
        dict[str, object],
        str,
    ],
    ...,
] = (
    (
        "channel_base_current_equal_last",
        CHANNEL_BASE_SAMPLE_CURRENT_EQUAL_LAST,
        "current_equal_last",
    ),
    (
        "channel_zero_current_id",
        CHANNEL_ZERO_CURRENT_ID,
        "current_zero",
    ),
    (
        "channel_missing_values",
        {},
        "missing_values",
    ),
    (
        "channel_normal",
        CHANNEL_BASE_SAMPLE,
        "normal_case",
    ),
)

GET_FILTERED_KEYS_EXAMPLES: tuple[
    tuple[
        object,
        list[str],
        str,
    ],
    ...,
] = (
    (
        CHANNEL_INFO_BY_NAME(
            "channel_new",
        ),
        [],
        "channel_new",
    ),
    (
        {},
        [],
        "empty_input",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_base_current_equal_last",
            "channel_base_current_lt_last",
            "channel_negative_current_id",
            "channel_new",
            "channel_zero_current_id",
        ]),
        [
            "channel_base_current_lt_last",
            "channel_negative_current_id",
        ],
        "mixed_channels_some_update",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_scanned_found_configs",
            "channel_scanned_no_found_configs",
            "channel_unavailable",
        ]),
        [],
        "no_channels_need_update",
    ),
    (
        CHANNEL_INFO_BY_NAME(
            "channel_available",
        ),
        [
            "channel_available",
        ],
        "single_channel_update",
    ),
)

GET_NORMALIZED_CURRENT_ID_EXAMPLES: tuple[
    tuple[
        dict[str, object],
        int,
        str,
    ],
    ...,
] = (
    (
        CHANNEL_BASE_SAMPLE_CURRENT_GT_LAST,
        min(
            NUM2,
            NUM3,
        ),
        "current_gt_last",
    ),
    (
        CHANNEL_ZERO_CURRENT_ID,
        max(
            DEFAULT_CURRENT_ID,
            NUM3 + (NUM2 - NUM2),
        ),
        "current_zero",
    ),
    (
        {},
        max(
            DEFAULT_CURRENT_ID,
            DEFAULT_LAST_ID,
        ),
        "empty_dict",
    ),
    (
        CHANNEL_DEFAULT_LAST_ID,
        DEFAULT_CURRENT_ID,
        "last_default",
    ),
    (
        {
            **CHANNEL_BASE_SAMPLE,
            "current_id": -(NUM3 * 2),
        },
        max(
            DEFAULT_CURRENT_ID,
            NUM3 + -(NUM3 * 2),
        ),
        "negative_below_default",
    ),
    (
        CHANNEL_NEGATIVE_CURRENT_ID,
        max(
            DEFAULT_CURRENT_ID,
            NUM3 + -NUM2,
        ),
        "negative_current",
    ),
    (
        CHANNEL_BASE_SAMPLE,
        min(
            NUM2,
            NUM3,
        ),
        "normal_case",
    ),
)

GET_SORTED_KEYS_EXAMPLES: tuple[
    tuple[
        object,
        bool,
        bool,
        list[str],
        str,
    ],
    ...,
] = (
    (
        CHANNELS_SAMPLE,
        True,
        False,
        [
            "channel_available",
            "channel_base_current_lt_last",
            "channel_negative_current_id",
        ],
        "apply_filter",
    ),
    (
        {},
        False,
        False,
        [],
        "empty_input",
    ),
    (
        CHANNELS_FROM_NAMES_SAMPLE,
        False,
        False,
        sorted(
            CHANNEL_NAMES_SAMPLE,
            reverse=False,
        ),
        "equal_values_normal_sort",
    ),
    (
        CHANNELS_FROM_NAMES_SAMPLE,
        False,
        True,
        sorted(
            CHANNEL_NAMES_SAMPLE,
            reverse=True,
        ),
        "equal_values_reverse_sort",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_available",
            "channel_base_current_gt_last",
            "channel_negative_current_id",
            "channel_new",
            "channel_unavailable",
        ]),
        False,
        False,
        [
            "channel_base_current_gt_last",
            "channel_new",
            "channel_unavailable",
            "channel_available",
            "channel_negative_current_id",
        ],
        "normal_sort",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_base_current_gt_last",
            "channel_negative_current_id",
            "channel_unavailable",
        ]),
        False,
        False,
        [
            "channel_base_current_gt_last",
            "channel_unavailable",
            "channel_negative_current_id",
        ],
        "normalized_channels_sort",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_available",
            "channel_base_current_gt_last",
            "channel_negative_current_id",
            "channel_new",
            "channel_unavailable",
        ]),
        False,
        True,
        [
            "channel_negative_current_id",
            "channel_available",
            "channel_unavailable",
            "channel_new",
            "channel_base_current_gt_last",
        ],
        "reverse_sort",
    ),
    (
        CHANNEL_INFO_BY_NAME(
            "channel_available",
        ),
        False,
        False,
        [
            "channel_available",
        ],
        "single_channel",
    ),
)

NORMALIZE_CHANNEL_NAMES_EXAMPLES: tuple[
    tuple[
        object,
        object,
        str,
    ],
    ...,
] = (
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_lower_one",
            "channel_lower_two",
        ]),
        CHANNEL_INFO_BY_NAMES([
            "channel_lower_one",
            "channel_lower_two",
        ]),
        "all_channel_names_lowercase",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "CHANNEL_UPPER_ONE",
            "CHANNEL_UPPER_TWO",
        ]),
        CHANNEL_INFO_BY_NAMES([
            "channel_upper_one",
            "channel_upper_two",
        ]),
        "all_channel_names_uppercase",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_Available",
            "channel_available",
            "channel_new",
            "channel_NEW",
            "channel_unavailable",
        ]),
        {
            "channel_available": {
                **CHANNEL_BASE,
            },
            **CHANNEL_INFO_BY_NAMES([
                "channel_new",
                "channel_unavailable",
            ]),
        },
        "duplicates_keep_first",
    ),
    (
        {
            name: {
                **CHANNEL_BASE,
            }
            for name in (
                NUM1,
                f"channel_{NUM2}",
                float(NUM3),
            )
        },
        {
            str(name): {
                **CHANNEL_BASE,
            }
            for name in (
                NUM1,
                f"channel_{NUM2}",
                float(NUM3),
            )
        },
        "mixed_key_types",
    ),
    (
        {},
        {},
        "no_channels",
    ),
)

PRINT_CHANNEL_INFO_VARIOUS_EXAMPLES: tuple[
    tuple[
        object,
        str,
    ],
    ...,
] = (
    (
        CHANNELS_SAMPLE,
        "mixed_channels",
    ),
    (
        {},
        "no_channels",
    ),
    (
        CHANNEL_INFO_BY_NAME(
            "channel_base_current_equal_last",
        ),
        "single_channel_equal",
    ),
    (
        CHANNEL_INFO_BY_NAMES([
            "channel_base_current_gt_last",
            "channel_base_current_lt_last",
        ]),
        "two_channels",
    ),
)

PROCESS_CHANNELS_CALLS_EXAMPLES: tuple[
    tuple[
        int,
        bool,
        bool,
        str,
    ],
    ...,
] = (
    (
        MESSAGE_OFFSET,
        False,
        True,
        "delete_and_update",
    ),
    (
        MESSAGE_OFFSET - MESSAGE_OFFSET,
        False,
        False,
        "skip_delete_no_offset",
    ),
    (
        MESSAGE_OFFSET,
        False,
        False,
        "skip_delete_update_offset",
    ),
)

SORT_CHANNEL_NAMES_EXAMPLES: tuple[
    tuple[
        list[str],
        str,
    ],
    ...,
] = (
    (
        [
            "channel_a",
            "channel_b",
            "channel_c",
        ],
        "already_sorted",
    ),
    (
        [
            "channel_b",
            "channel_c",
            "CHANNEL_B",
        ],
        "base_case",
    ),
    (
        [
            "channel_c2",
            "CHANNEL_C1",
            "channel_b3",
            "CHANNEL_B2",
        ],
        "digits_letters",
    ),
    (
        [
            "channel_a",
            "CHANNEL_A",
            "channel_b",
            "CHANNEL_B",
        ],
        "duplicates",
    ),
    (
        [],
        "empty_list",
    ),
    (
        [
            "",
            "channel_a",
            "CHANNEL_A",
        ],
        "empty_strings",
    ),
)

UPDATE_COUNT_AND_LAST_ID_EXAMPLES: tuple[
    tuple[
        str,
        dict[str, object],
        int,
        dict[str, object],
        str,
    ],
    ...,
] = (
    (
        "channel_base",
        {
            **CHANNEL_BASE_SAMPLE,
        },
        LAST_POST_ID,
        {
            **CHANNEL_BASE_SAMPLE,
            "count": max(
                NUM1,
                CHANNEL_ACTIVE_THRESHOLD,
            ),
            "last_id": LAST_POST_ID,
        },
        "basic_update_last_id",
    ),
    (
        "channel_base_count_below_threshold",
        {
            **CHANNEL_SCANNED_NO_FOUND_CONFIGS,
        },
        LAST_POST_ID,
        {
            **CHANNEL_SCANNED_NO_FOUND_CONFIGS,
            "count": max(
                DEFAULT_COUNT,
                CHANNEL_ACTIVE_THRESHOLD,
            ),
            "last_id": LAST_POST_ID,
        },
        "count_below_threshold",
    ),
    (
        "channel_base_default_last_id_decrease_count",
        {
            **CHANNEL_DEFAULT_LAST_ID,
            "count": NUM1,
        },
        DEFAULT_LAST_ID,
        {
            **CHANNEL_DEFAULT_LAST_ID,
            "count": min(
                NUM1 - 1,
                DEFAULT_COUNT,
            ),
        },
        "default_last_id_decrease_count",
    ),
    (
        "channel_base_empty_channel_info",
        {},
        LAST_POST_ID,
        {
            "count": max(
                DEFAULT_COUNT,
                CHANNEL_ACTIVE_THRESHOLD,
            ),
            "last_id": LAST_POST_ID,
        },
        "empty_channel_info",
    ),
    (
        "channel_base_last_id_equal_last_post_id",
        {
            **CHANNEL_BASE_SAMPLE,
        },
        NUM3,
        {
            **CHANNEL_BASE_SAMPLE,
            "count": max(
                NUM1,
                CHANNEL_ACTIVE_THRESHOLD,
            ),
        },
        "last_id_equal_last_post_id",
    ),
    (
        "channel_base_missing_count",
        {
            **CHANNEL_MISSING_COUNT,
        },
        LAST_POST_ID,
        {
            **CHANNEL_MISSING_COUNT,
            "count": max(
                DEFAULT_COUNT,
                CHANNEL_ACTIVE_THRESHOLD,
            ),
            "last_id": LAST_POST_ID,
        },
        "missing_count",
    ),
    (
        "channel_base_missing_last_id",
        {
            **CHANNEL_MISSING_LAST_ID,
        },
        LAST_POST_ID,
        {
            **CHANNEL_MISSING_LAST_ID,
            "count": max(
                DEFAULT_COUNT,
                CHANNEL_ACTIVE_THRESHOLD,
            ),
            "last_id": LAST_POST_ID,
        },
        "missing_last_id",
    ),
    (
        "channel_base_negative_last_post_id",
        {
            **CHANNEL_BASE_SAMPLE,
        },
        DEFAULT_LAST_ID,
        {
            **CHANNEL_BASE_SAMPLE,
            "count": max(
                NUM1,
                CHANNEL_ACTIVE_THRESHOLD,
            ),
            "last_id": DEFAULT_LAST_ID,
        },
        "negative_last_post_id",
    ),
)

UPDATE_WITH_NEW_CHANNELS_EXAMPLES: tuple[
    tuple[
        object,
        list[str],
        list[str],
        str,
    ],
    ...,
] = (
    (
        CHANNELS_FROM_NAMES_SAMPLE,
        [
            "channel_add_a",
            "channel_add_c",
            "channel_add_b",
            "CHANNEL_ADD_A",
        ],
        [
            *CHANNEL_NAMES_SAMPLE,
            "channel_add_a",
            "CHANNEL_ADD_A",
            "channel_add_b",
            "channel_add_c",
        ],
        "add_new_channels",
    ),
    (
        CHANNELS_SAMPLE,
        [],
        list(CHANNELS_SAMPLE),
        "no_new_channels",
    ),
    (
        {},
        [
            "Channel_new_b",
            "CHANNEL_NEW_A",
            "channel_new_B",
            "channel_new_a",
        ],
        [
            "CHANNEL_NEW_A",
            "channel_new_a",
            "Channel_new_b",
            "channel_new_B",
        ],
        "only_new_channels",
    ),
)
