from core.constants.common import (
    CHANNEL_FAILED_ATTEMPTS_THRESHOLD,
    CHANNEL_MIN_ID_DIFF,
    CHANNEL_REMOVE_THRESHOLD,
    CHANNEL_STATE_AVAILABLE,
    CHANNEL_STATE_UNAVAILABLE,
    DEFAULT_CHANNEL_VALUES,
    DEFAULT_COUNT,
    DEFAULT_CURRENT_ID,
    DEFAULT_LAST_ID,
    DEFAULT_STATE,
)
from core.constants.formats import (
    FORMAT_CHANNEL_CHANGE,
)
from core.constants.messages.info import (
    MESSAGE_INFO_CHANNEL_DELETE_SKIPPED,
)
from core.constants.messages.warning import (
    MESSAGE_WARNING_NO_CHANNELS_TO_DISPLAY,
)
from core.constants.templates.debug.channel import (
    TEMPLATE_DEBUG_CHANNEL_ASSIGNMENT_OFFSET_APPLIED,
    TEMPLATE_DEBUG_CHANNEL_MISSING_ADD_COMPLETED,
    TEMPLATE_DEBUG_CHANNEL_RESET_SKIPPED_NO_CHANGES,
)
from core.constants.templates.error import (
    TEMPLATE_ERROR_INVALID_OVERRIDE_FIELDS,
)
from core.constants.templates.info.channel import (
    TEMPLATE_INFO_CHANNEL_ASSIGNMENT_APPLIED,
    TEMPLATE_INFO_CHANNEL_ASSIGNMENT_SKIPPED,
    TEMPLATE_INFO_CHANNEL_RESET_SKIPPED,
    TEMPLATE_INFO_CHANNEL_RESET_TOTAL,
    TEMPLATE_INFO_CHANNELS_STATUS_COMPLETED,
    TEMPLATE_INFO_CHANNELS_STATUS_STARTED,
)
from core.constants.templates.title import (
    TEMPLATE_TITLE_CHANNEL_DELETE,
    TEMPLATE_TITLE_CHANNEL_INFO,
    TEMPLATE_TITLE_CHANNEL_RESET,
)
from core.constants.templates.warning import (
    TEMPLATE_WARNING_CHANNEL_ASSIGNMENT_OFFSET_SKIPPED,
    TEMPLATE_WARNING_INVALID_OFFSET,
)

__all__ = [
    "CHANNEL_FAILED_ATTEMPTS_THRESHOLD",
    "CHANNEL_MIN_ID_DIFF",
    "CHANNEL_REMOVE_THRESHOLD",
    "CHANNEL_STATE_AVAILABLE",
    "CHANNEL_STATE_UNAVAILABLE",
    "DEFAULT_CHANNEL_VALUES",
    "DEFAULT_COUNT",
    "DEFAULT_CURRENT_ID",
    "DEFAULT_LAST_ID",
    "DEFAULT_STATE",
    "FORMAT_CHANNEL_CHANGE",
    "LAST_POST_ID",
    "MESSAGE_INFO_CHANNEL_DELETE_SKIPPED",
    "MESSAGE_OFFSET",
    "MESSAGE_WARNING_NO_CHANNELS_TO_DISPLAY",
    "NUM1",
    "NUM2",
    "NUM3",
    "TEMPLATE_DEBUG_CHANNEL_ASSIGNMENT_OFFSET_APPLIED",
    "TEMPLATE_DEBUG_CHANNEL_MISSING_ADD_COMPLETED",
    "TEMPLATE_DEBUG_CHANNEL_RESET_SKIPPED_NO_CHANGES",
    "TEMPLATE_ERROR_INVALID_OVERRIDE_FIELDS",
    "TEMPLATE_INFO_CHANNELS_STATUS_COMPLETED",
    "TEMPLATE_INFO_CHANNELS_STATUS_STARTED",
    "TEMPLATE_INFO_CHANNEL_ASSIGNMENT_APPLIED",
    "TEMPLATE_INFO_CHANNEL_ASSIGNMENT_SKIPPED",
    "TEMPLATE_INFO_CHANNEL_RESET_SKIPPED",
    "TEMPLATE_INFO_CHANNEL_RESET_TOTAL",
    "TEMPLATE_TITLE_CHANNEL_DELETE",
    "TEMPLATE_TITLE_CHANNEL_INFO",
    "TEMPLATE_TITLE_CHANNEL_RESET",
    "TEMPLATE_WARNING_CHANNEL_ASSIGNMENT_OFFSET_SKIPPED",
    "TEMPLATE_WARNING_INVALID_OFFSET",
]

LAST_POST_ID: int = 1111
MESSAGE_OFFSET: int = 2222

NUM1: int = 11111
NUM2: int = 22222
NUM3: int = 33333
