from core.constants.common import (
    CHANNEL_ACTIVE_THRESHOLD,
    CHANNEL_FAILED_ATTEMPTS_THRESHOLD,
    CHANNEL_MIN_ID_DIFF,
    CHANNEL_REMOVE_THRESHOLD,
    DEFAULT_CHANNEL_VALUES,
    DEFAULT_COUNT,
    DEFAULT_CURRENT_ID,
    DEFAULT_LAST_ID,
)
from core.constants.messages import (
    MESSAGE_CHANNEL_DELETE_SKIPPED,
    MESSAGE_CHANNEL_SHOW_INFO,
)
from core.constants.templates import (
    TEMPLATE_CHANNEL_ASSIGNMENT_APPLIED,
    TEMPLATE_CHANNEL_ASSIGNMENT_OFFSET_APPLIED,
    TEMPLATE_CHANNEL_ASSIGNMENT_OFFSET_SKIPPED,
    TEMPLATE_CHANNEL_ASSIGNMENT_SKIPPED,
    TEMPLATE_CHANNEL_LEFT_TO_CHECK,
    TEMPLATE_CHANNEL_LOG_STATUS,
    TEMPLATE_CHANNEL_LOG_UPDATE,
    TEMPLATE_CHANNEL_MISSING_ADD_COMPLETED,
    TEMPLATE_CHANNEL_TOTAL_AVAILABLE,
    TEMPLATE_CHANNEL_TOTAL_MESSAGES,
    TEMPLATE_ERROR_INVALID_OFFSET,
    TEMPLATE_FORMAT_STRING_QUOTED_NAME,
    TEMPLATE_TITLE_DEBUG_OFFSET,
    TEMPLATE_TITLE_DELETING_CHANNEL,
)

__all__ = [
    "CHANNEL_ACTIVE_THRESHOLD",
    "CHANNEL_FAILED_ATTEMPTS_THRESHOLD",
    "CHANNEL_MIN_ID_DIFF",
    "CHANNEL_REMOVE_THRESHOLD",
    "DEFAULT_CHANNEL_VALUES",
    "DEFAULT_COUNT",
    "DEFAULT_CURRENT_ID",
    "DEFAULT_LAST_ID",
    "LAST_POST_ID",
    "MESSAGE_CHANNEL_DELETE_SKIPPED",
    "MESSAGE_CHANNEL_SHOW_INFO",
    "MESSAGE_OFFSET",
    "NUM1",
    "NUM2",
    "NUM3",
    "TEMPLATE_CHANNEL_ASSIGNMENT_APPLIED",
    "TEMPLATE_CHANNEL_ASSIGNMENT_OFFSET_APPLIED",
    "TEMPLATE_CHANNEL_ASSIGNMENT_OFFSET_SKIPPED",
    "TEMPLATE_CHANNEL_ASSIGNMENT_SKIPPED",
    "TEMPLATE_CHANNEL_LEFT_TO_CHECK",
    "TEMPLATE_CHANNEL_LOG_STATUS",
    "TEMPLATE_CHANNEL_LOG_UPDATE",
    "TEMPLATE_CHANNEL_MISSING_ADD_COMPLETED",
    "TEMPLATE_CHANNEL_TOTAL_AVAILABLE",
    "TEMPLATE_CHANNEL_TOTAL_MESSAGES",
    "TEMPLATE_ERROR_INVALID_OFFSET",
    "TEMPLATE_FORMAT_STRING_QUOTED_NAME",
    "TEMPLATE_TITLE_DEBUG_OFFSET",
    "TEMPLATE_TITLE_DELETING_CHANNEL",
]

LAST_POST_ID = 1111
MESSAGE_OFFSET = 2222

NUM1 = 11111
NUM2 = 22222
NUM3 = 33333
