from core.typing import (
    TableStr,
)

__all__ = [
    "TABLE_CHANNELS_STATUS_COLUMN_CHANNEL",
    "TABLE_CHANNELS_STATUS_COLUMN_CURRENT_ID",
    "TABLE_CHANNELS_STATUS_COLUMN_DIFF",
    "TABLE_CHANNELS_STATUS_COLUMN_LAST_ID",
    "TABLE_CHANNELS_STATUS_COLUMN_NO",
    "TABLE_CHANNELS_STATUS_TITLE",
    "TABLE_CHANNELS_UPDATES_COLUMN_CHANNEL",
    "TABLE_CHANNELS_UPDATES_COLUMN_NEW_LAST_ID",
    "TABLE_CHANNELS_UPDATES_COLUMN_NO",
    "TABLE_CHANNELS_UPDATES_COLUMN_OLD_LAST_ID",
    "TABLE_CHANNELS_UPDATES_TITLE",
    "TABLE_CONFIGS_EXTRACT_COLUMN_CHANNEL",
    "TABLE_CONFIGS_EXTRACT_COLUMN_FOUND",
    "TABLE_CONFIGS_EXTRACT_COLUMN_NO",
    "TABLE_CONFIGS_EXTRACT_COLUMN_TOTAL",
    "TABLE_CONFIGS_EXTRACT_TITLE",
]

TABLE_CHANNELS_STATUS_COLUMN_CHANNEL: TableStr = (
    "Channel"
)
TABLE_CHANNELS_STATUS_COLUMN_CURRENT_ID: TableStr = (
    "Current ID"
)
TABLE_CHANNELS_STATUS_COLUMN_DIFF: TableStr = (
    "Diff"
)
TABLE_CHANNELS_STATUS_COLUMN_LAST_ID: TableStr = (
    "Last ID"
)
TABLE_CHANNELS_STATUS_COLUMN_NO: TableStr = (
    "No"
)
TABLE_CHANNELS_STATUS_TITLE: TableStr = (
    "Channels Status"
)
TABLE_CHANNELS_UPDATES_COLUMN_CHANNEL: TableStr = (
    "Channel"
)
TABLE_CHANNELS_UPDATES_COLUMN_NEW_LAST_ID: TableStr = (
    "New Last ID"
)
TABLE_CHANNELS_UPDATES_COLUMN_NO: TableStr = (
    "No"
)
TABLE_CHANNELS_UPDATES_COLUMN_OLD_LAST_ID: TableStr = (
    "Old Last ID"
)
TABLE_CHANNELS_UPDATES_TITLE: TableStr = (
    "Channels Updates"
)
TABLE_CONFIGS_EXTRACT_COLUMN_CHANNEL: TableStr = (
    "Channel"
)
TABLE_CONFIGS_EXTRACT_COLUMN_FOUND: TableStr = (
    "Found"
)
TABLE_CONFIGS_EXTRACT_COLUMN_NO: TableStr = (
    "No"
)
TABLE_CONFIGS_EXTRACT_COLUMN_TOTAL: TableStr = (
    "Total"
)
TABLE_CONFIGS_EXTRACT_TITLE: TableStr = (
    "Configs Extract"
)
