__all__ = [
    "V2RAY_PATTERNS_BY_PROTOCOL_MATCH_EXAMPLES",
    "V2RAY_PATTERNS_BY_PROTOCOL_VALID_EXAMPLES",
]

V2RAY_PATTERNS_BY_PROTOCOL_MATCH_EXAMPLES: tuple[
    tuple[
        str,
        str,
    ],
    ...,
] = (
    (
        "anytls",
        "anytls://password@example.com:443",
    ),
    (
        "hy2",
        "hy2://password@example.com:443",
    ),
    (
        "hysteria2",
        "hysteria2://password@example.com:443",
    ),
    (
        "ss",
        "ss://aes-256-gcm:password@example.com:8388",
    ),
    (
        "ss",
        "ss://YWVzLTI1Ni1nY206cGFzc3dvcmQ=@example.com:8388",
    ),
    (
        "ss",
        "ss://YWVzLTI1Ni1nY206cGFzc3dvcmRAZXhhbXBsZS5jb206ODM4OA==#node1",
    ),
    (
        "ssr",
        "ssr://ZXhhbXBsZS5jb206NDQzOm9yaWdpbjphZXMtMjU2LWNmYjpwbGFpbjpwYXNzd29yZA==",
    ),
    (
        "trojan",
        "trojan://password@example.com:443",
    ),
    (
        "tuic",
        "tuic://uuid:password@example.com:443",
    ),
    (
        "vless",
        "vless://uuid@example.com:443",
    ),
    (
        "vmess",
        "vmess://uuid@example.com:443",
    ),
    (
        "vmess",
        "vmess://ewogICJhZGQiOiAiZXhhbXBsZS5jb20iCn0=",
    ),
    (
        "wireguard",
        "wireguard://privatekey@example.com:51820",
    ),
)

V2RAY_PATTERNS_BY_PROTOCOL_VALID_EXAMPLES: tuple[
    tuple[
        str,
        int,
    ],
    ...,
] = (
    (
        "anytls",
        1,
    ),
    (
        "hy2",
        1,
    ),
    (
        "hysteria2",
        1,
    ),
    (
        "ss",
        2,
    ),
    (
        "ssr",
        1,
    ),
    (
        "trojan",
        1,
    ),
    (
        "tuic",
        1,
    ),
    (
        "vless",
        1,
    ),
    (
        "vmess",
        2,
    ),
    (
        "wireguard",
        1,
    ),
)
